import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import Layout from "../components/layout";

// @ts-ignore :: NEED TO FIX IT LATER
// const fetcher = (...args:any) => fetch(...args).then(res => res.json())

export default function Home(props: any) {
  // const { data } = useSWR(`/api/posts/`, fetcher);

  // console.log(data)
  // if (!data) {
  //   return 'Loading...';
  // }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout> </Layout>

      <footer>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  );
}
